---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: {{ include "nextcloud.ns" . }}
  labels:
    app: nextcloud
data:
{{- range $key, $value := .Values.nextcloud.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
